[book]
authors = ["Gilad Naaman"]
language = "en"
src = "src"
title = "Gilad's Sonic Research Book"

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.kroki-preprocessor]
command = "mdbook-kroki-preprocessor"
#endpoint = "http://localhost:8000"
endpoint = "https://kroki.io"